- name: Install Docker
  ansible.builtin.package:
    name: docker.io
    state: present

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ docker_network }}"
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true