- name: Enable passwordless sudo for azureuser
  hosts: all
  become: yes
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password for azureuser"
      private: yes

  tasks:
    - name: Add azureuser to sudoers for passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^azureuser'
        line: 'azureuser ALL=(ALL) NOPASSWD:ALL'
        state: present
      become: yes

    - name: Validate sudoers file
      ansible.builtin.command: visudo -cf /etc/sudoers
      become: yes