name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  terraform-infra:
    runs-on: ubuntu-latest
    env:
      TF_VAR_location: ${{ secrets.TF_VAR_LOCATION }}
      TF_VAR_resource_group_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
      TF_VAR_storage_account_name: ${{ secrets.TF_STORAGE_ACCOUNT }}
      TF_VAR_container_name: ${{ secrets.TF_CONTAINER_NAME }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Whitelist GitHub Runner IP
        uses: azure/CLI@v1
        with:
            inlineScript: |
                set -eu
                agentIP=$(curl -s https://api.ipify.org/)
                echo "Adding firewall rule for runner IP: $agentIP"
                az storage account network-rule add \
                    --resource-group "${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}" \
                    --account-name "${{ secrets.TF_STORAGE_ACCOUNT }}" \
                    --ip-address $agentIP
                sleep 30

      - name: Init & Apply KeyVault
        working-directory: terraform/key-vault
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Init & Apply VM Stack
        working-directory: terraform/vm-stack
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Remove GitHub Runner IP
        if: always()
        uses: azure/CLI@v1
        with:
            inlineScript: |
                set -eu
                agentIP=$(curl -s https://api.ipify.org/)
                echo "Removing firewall rule for runner IP: $agentIP"
                az storage account network-rule remove \
                    --resource-group "${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}" \
                    --account-name "${{ secrets.TF_STORAGE_ACCOUNT }}" \
                    --ip-address $agentIP