name: Destroy Infra

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_location: ${{ secrets.TF_VAR_LOCATION }}
      TF_VAR_resource_group_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
      TF_VAR_storage_account_name: ${{ secrets.TF_STORAGE_ACCOUNT }}
      TF_VAR_container_name: ${{ secrets.TF_CONTAINER_NAME }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.AZURE_VM_PUBLIC_SSH_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy VM Stack
        if: ${{ github.event.inputs.target == 'vm-stack' || github.event.inputs.target == 'all' }}
        working-directory: terraform/vm-stack
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_RG_NAME }}" \
                         -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT }}" \
                         -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
                         -backend-config="key=vm-stack.tfstate"

          terraform destroy -auto-approve

      - name: Destroy Key Vault
        working-directory: terraform/key-vault
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_RG_NAME }}" \
                         -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT }}" \
                         -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" \
                         -backend-config="key=demo/kv.tfstate"

          terraform destroy -auto-approve